{
 "title": "Eris",
 "description": "BlockIRC dashboard",
 "tags": [ "eris" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Up",
   "type": "singlestat",
   "description": "BlockIRC up status",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"BlockIRC\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "BlockIRC server uptime",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "dtdurationms",
   "valueName": "current",
   "targets": [
    { "expr": "eris_server_uptime / 1e6" }
   ]
  },
  {
   "title": "Commands",
   "type": "singlestat",
   "description": "Number of commands processed",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "eris_client_commands" }
   ]
  },
  {
   "title": "Connections",
   "type": "singlestat",
   "description": "Active connections",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "eris_server_connections" }
   ]
  },
  {
   "title": "Connections",
   "type": "singlestat",
   "description": "Active connections",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "eris_server_connections" }
   ]
  },
  {
   "title": "Channels",
   "type": "singlestat",
   "description": "Number of active channels",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "eris_server_channels" }
   ]
  },
  {
   "title": "Client Latency",
   "type": "graph",
   "description": "Client latency",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "eris_client_ping_latency_seconds_sum / eris_client_ping_latency_seconds_count",
     "legendFormat": "avg"
    },
    {
     "expr": "eris_client_ping_latency_seconds{quantile=\"0.5\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "eris_client_ping_latency_seconds{quantile=\"0.9\"}",
     "legendFormat": "p90"
    },
    {
     "expr": "eris_client_ping_latency_seconds{quantile=\"0.95\"}",
     "legendFormat": "p95"
    },
    {
     "expr": "eris_client_ping_latency_seconds{quantile=\"0.99\"}",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Command Latency",
   "type": "graph",
   "description": "Processing latency of commands",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "eris_client_command_duration_seconds_sum / eris_client_command_duration_seconds_count",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Command Rate",
   "type": "graph",
   "description": "Rate of commands processed over 5m",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(eris_client_commands[5m])",
     "legendFormat": "commands/s"
    }
   ]
  },
  {
   "title": "Message Rate",
   "type": "graph",
   "description": "Rate of messages exchanged over 5m",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(eris_client_messages[5m])",
     "legendFormat": "messages/s"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Memory usage of process (resident, virtual)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"eris\"}",
     "legendFormat": "rss"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"eris\"}",
     "legendFormat": "vm"
    }
   ]
  },
  {
   "title": "Memory Allocations",
   "type": "graph",
   "description": "Memory allocations (bytes, heap, stack)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"eris\"}",
     "legendFormat": "bytes"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"eris\"}",
     "legendFormat": "heap"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"eris\"}",
     "legendFormat": "stack"
    }
   ]
  },
  {
   "title": "Threads / Goroutines",
   "type": "graph",
   "description": "Active threads / goroutines",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "go_threads{job=\"eris\"}",
     "legendFormat": "threads"
    },
    {
     "expr": "go_goroutines{job=\"eris\"}",
     "legendFormat": "goroutines"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "graph",
   "description": "Garbage Collection duration",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds_sum{job=\"eris\"} / go_gc_duration_seconds_count{job=\"eris\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"eris\", job=\"eris\", quantile=\"0.25\"}",
     "legendFormat": "p25"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"eris\", quantile=\"0.5\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"eris\", quantile=\"0.75\"}",
     "legendFormat": "p75"
    }
   ]
  }
 ]
}